# Generated by Django 4.2.6 on 2023-10-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_down_2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
